'use strict'
console.log()
console.group('# package resolution')
console.log(`require('pino')`, '\t', '  =>', import.meta.resolve('pino'))
console.log(`require('standard')`, '\t', '  =>', import.meta.resolve('standard'))
console.groupEnd('')
console.log()
console.group('# directory resolution')
console.log(`require('.')`, '\t\t', '  =>', import.meta.resolve('.'))
console.log(`require('../pckt')`, '=>', import.meta.resolve('../pckt'))
console.groupEnd()
console.log()
console.group('# file resolution')
console.log(`require('./format')`, '\t', '  =>', import.meta.resolve('./format'))
console.log(`require('./format.js')`, '  =>', import.meta.resolve('./format.js'))
console.groupEnd()
console.log()
console.group('# core APIs resolution')
console.log(`require('fs')`, '\t', '  =>', import.meta.resolve('fs'))
console.log(`require('util')`, '\t', '  =>', import.meta.resolve('util'))
console.groupEnd()
console.log()
